// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfLDIqYDuCdE_GH7_JOZywWzC4kJpEWLA',
    appId: '1:388685394261:web:0c8fc3be2e051f4265bfdc',
    messagingSenderId: '388685394261',
    projectId: 'fit-project-12660',
    authDomain: 'fit-project-12660.firebaseapp.com',
    storageBucket: 'fit-project-12660.firebasestorage.app',
    measurementId: 'G-H82FYBF63K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYbSqqfCqCmKARuBaEUh6trw1SMuNwi0A',
    appId: '1:388685394261:android:1b11b57d557f696765bfdc',
    messagingSenderId: '388685394261',
    projectId: 'fit-project-12660',
    storageBucket: 'fit-project-12660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMJ2HOZ2M7L5BLogGbZNl3eyjE7pNHfwk',
    appId: '1:388685394261:ios:7c29d8dbba5e79f965bfdc',
    messagingSenderId: '388685394261',
    projectId: 'fit-project-12660',
    storageBucket: 'fit-project-12660.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
